import react from '@vitejs/plugin-react'
import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { defineConfig, loadEnv } from 'vite'
import { VitePWA } from 'vite-plugin-pwa'

const rootDir = dirname(fileURLToPath(import.meta.url))

function writeFcmSw(env: Record<string, string>, base: string) {
  const cfg = {
    apiKey: env.VITE_FIREBASE_API_KEY || '',
    authDomain: env.VITE_FIREBASE_AUTH_DOMAIN || '',
    projectId: env.VITE_FIREBASE_PROJECT_ID || '',
    storageBucket: env.VITE_FIREBASE_STORAGE_BUCKET || '',
    messagingSenderId: env.VITE_FIREBASE_MESSAGING_SENDER_ID || '',
    appId: env.VITE_FIREBASE_APP_ID || '',
  }
  const body = `/* auto-generated by vite — FCM background SW */
importScripts('https://www.gstatic.com/firebasejs/10.14.1/firebase-app-compat.js')
importScripts('https://www.gstatic.com/firebasejs/10.14.1/firebase-messaging-compat.js')

firebase.initializeApp(${JSON.stringify(cfg, null, 2)})

try {
  firebase.messaging().onBackgroundMessage((payload) => {
    const title = payload.notification?.title || 'İş Takip'
    const body = payload.notification?.body || ''
    self.registration.showNotification(title, {
      body,
      icon: '${base}pwa-192.png',
      data: payload.data || {},
    })
  })
} catch (_) {}

self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((list) => {
      for (const client of list) {
        if ('focus' in client) return client.focus()
      }
      if (clients.openWindow) return clients.openWindow('${base}')
    }),
  )
})
`
  writeFileSync(resolve(rootDir, 'public/firebase-messaging-sw.js'), body)
}

const isGitHubPages = process.env.GITHUB_PAGES === 'true'
const repoName = process.env.VITE_REPO_NAME || 'istakip'
const base = isGitHubPages ? `/${repoName}/` : '/'

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '')
  writeFcmSw(env, base)

  return {
    base,
    plugins: [
      react(),
      VitePWA({
        registerType: 'autoUpdate',
        includeAssets: [
          'favicon.svg',
          'apple-touch-icon.png',
          'logo.svg',
          'firebase-messaging-sw.js',
        ],
        manifest: {
          name: 'İş Takip',
          short_name: 'İş Takip',
          description: 'Alan ve grup işlerini birlikte takip edin',
          theme_color: '#1a5c4a',
          background_color: '#f3f6f4',
          display: 'standalone',
          orientation: 'portrait',
          start_url: base,
          scope: base,
          icons: [
            {
              src: 'pwa-192.png',
              sizes: '192x192',
              type: 'image/png',
            },
            {
              src: 'pwa-512.png',
              sizes: '512x512',
              type: 'image/png',
            },
            {
              src: 'pwa-512.png',
              sizes: '512x512',
              type: 'image/png',
              purpose: 'maskable',
            },
          ],
        },
        workbox: {
          globPatterns: ['**/*.{js,css,html,ico,png,svg,woff2}'],
        },
      }),
    ],
  }
})
